version: "3.5"

services:

  synapse:
    image: matrixdotorg/synapse:${SYNAPSE_TAG}
    restart: unless-stopped
    container_name: synapse
    env_file: ./secrets/synapse.secrets
    volumes:
      - ./volumes/synapse:/data
    networks: 
      - matrix-local-net
      - matrix-proxy-net
    expose:
      - 8008
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matrix.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.matrix.entrypoints=websecure"
      - "traefik.http.routers.matrix.tls.certresolver=letsencrypt"
      - "traefik.http.routers.matrix.middlewares=matrix-hsts@docker"
      - "traefik.http.middlewares.matrix-hsts.headers.customresponseheaders.Strict-Transport-Security=max-age=15552000; includeSubDomains"
      - "traefik.docker.network=matrix-proxy-net"

  synapse-database:
    image: postgres:${POSTGRES_TAG}
    container_name: synapse-database
    restart: unless-stopped
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    env_file: ./secrets/database.secrets
    networks:
      - matrix-local-net

  synapse-turn:
    image: coturn/coturn:${COTURN_TAG}
    container_name: synapse-turn
    restart: unless-stopped
    volumes:
      - ./volumes/coturn/turnserver.conf:/etc/turnserver.conf:ro
    network_mode: host

networks: 
  matrix-local-net:
    name: matrix-local-net
  matrix-proxy-net:
    external: 
      name: matrix-proxy-net
